[project]
name = "mu-phd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jerry Kiely", email = "jerry@cowboysmall.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.9",
]


[project.scripts]
res-atam-xor = "research.atam.atam_xor:main"
res-atam-counter = "research.atam.atam_counter:main"
res-sdc-add = "research.sdc.sdc_add:main"
res-sdc-parity = "research.sdc.sdc_parity:main"

exp-adleman = "experiments.adleman.experiment:main"
exp-sdc = "experiments.sdc.experiment:main"


[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
namespace = true
