[project]
name = "mu-phd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jerry Kiely", email = "jerry@cowboysmall.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.9",
]


[project.scripts]
atam-xor = "research.atam.atam_xor:main"
atam-counter = "research.atam.atam_counter:main"
sdc-add = "research.sdc.sdc_add:main"
sdc-parity = "research.sdc.sdc_parity:main"

dp-coin-change-01 = "algorithms.dp.dp_coin_change_01:main"
dp-coin-change-02 = "algorithms.dp.dp_coin_change_02:main"
dp-knapsack-01 = "algorithms.dp.dp_knapsack_01:main"
dp-knapsack-02 = "algorithms.dp.dp_knapsack_02:main"

exp-adleman = "experiments.adleman.experiment:main"

exp-sdc-bt-parity = "experiments.sdc.bind_replace.experiment_parity:main"
exp-sdc-br-bitcopy = "experiments.sdc.bind_replace.experiment_bitcopy:main"

exp-sdc-bu-bitcopy = "experiments.sdc.bind_unbind.experiment_bitcopy:main"


[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
namespace = true
