[project]
name = "mu-phd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jerry Kiely", email = "jerry@cowboysmall.com" }
]
requires-python = ">=3.13, <3.14"
dependencies = [
    "matplotlib>=3.10.9",
    "nuad>=0.4.6",
    "nupack",
]


[project.scripts]
dp-coin-change-01 = "algorithms.dp.dp_coin_change_01:main"
dp-coin-change-02 = "algorithms.dp.dp_coin_change_02:main"
dp-knapsack-01 = "algorithms.dp.dp_knapsack_01:main"
dp-knapsack-02 = "algorithms.dp.dp_knapsack_02:main"

res-atam-xor = "research.atam.atam_xor:main"
res-atam-counter = "research.atam.atam_counter:main"
res-automata-r110 = "research.automata.cellular.rule_110:main"
res-automata-r30 = "research.automata.cellular.rule_30:main"
res-automata-r54 = "research.automata.cellular.rule_54:main"
res-sdc-add = "research.sdc.sdc_add:main"
res-sdc-parity = "research.sdc.sdc_parity:main"

exp-adleman = "experiments.adleman.experiment:main"
exp-sdc-br-bitcopy = "experiments.sdc.bind_replace.bitcopy.experiment:main"
exp-sdc-br-counter = "experiments.sdc.bind_replace.counter.experiment:main"
exp-sdc-br-parity = "experiments.sdc.bind_replace.parity.experiment:main"
exp-sdc-bu-bitcopy = "experiments.sdc.bind_unbind.experiment:main"

nupack-tut-analyze = "research.nupack.tutorial.analyze:main"
nupack-tut-design = "research.nupack.tutorial.design:main"


[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"


[tool.uv.build-backend]
namespace = true

[tool.uv.sources]
nupack = { path = "tools/nupack/nupack-4.0.2.0-cp313-cp313-linux_x86_64.whl" }
